### ISSUE TITLE
Why host network and privileged mode

### ISSUE THREAD

**Issue by olljanat** [stackhpc/docker-mlnx-neo#1]
Thanks for sharing this.

How ever I was wondering that does it really need host network and privileged mode?

**Comment by markgoddard** [comment]
Hi @olljanat, that's a good question. I expect you could run it without host networking by forwarding the right ports. I'm not sure whether it needs direct access to the networks it manages. To be honest, I've only ever run NEO in quite a specific environment - as an intermediary between OpenStack neutron and Mellanox UFM with InfiniBand networking. I'd be interested to hear if you can get it to work without these options.

**Comment by olljanat** [comment]
Closing as there is official Docker image available on https://hub.docker.com/r/mellanox/neo
